### ISSUE TITLE
When switch to legacy sepolicy?

### ISSUE THREAD

**Issue by windeqk** [AOSP-for-venus/platform_device_xiaomi_sm8350-common#1]
I think it will help you **a lot** with sepolicy

https://github.com/AOSP-for-venus/platform_device_xiaomi_sm8350-common/blob/8df576db2e2eb2bdf6e9680c6335ce69f5c0d9fa/BoardConfigCommon.mk#L174

Example commit:
https://github.com/tequilaOS/platform_device_xiaomi_umi/commit/e304e6c7f1e44fb64629a0de0780a57df0fe03c3

**Comment by ralph950412** [comment]
I know... But StatiX doesn't use that.

**Comment by ralph950412** [comment]
Anyways, I still appreciate your help!
